package config

import (
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"math/rand"
	"os"
	"sync"
	"time"
)

// Initialize creates the honeypot configuartion in the given directory.
func Initialize(path string) error {
	// Make sure path exists
	stat, err := os.Stat(path)
	if err != nil {
		return err
	}
	if !stat.Mode().IsDir() {
		return errors.New("intialization path must be a directory")
	}

	// Set up configuration file.
	cfg := defaultConfig()
	cfg.configurationDir = path

	log.Println("Generating private key...")
	privateKey, err := generateRSAKey()
	if err != nil {
		return err
	}

	log.Println("Creating configuration files...")
	configFiles := []struct {
		path     string
		contents []byte
	}{
		{cfg.ConfigurationPath(), defaultConfigData},
		{cfg.HostKeyPath(), privateKey},
		{cfg.PasswordsPath(), defaultPasswordsData},
		{cfg.RootFsTarPath(), rootFsData},
	}
	for _, configFile := range configFiles {
		if !exists(configFile.path) {
			log.Println("  ", configFile.path)
			if err := ioutil.WriteFile(configFile.path, configFile.contents, 0600); err != nil {
				return fmt.Errorf("couldn't write configuration file to %q: %v", configFile.path, err)
			}
		} else {
			log.Println("  ", configFile.path, "(skipped, it already exists)")
		}
	}

	// Make directories.
	log.Println("Making directories...")
	for _, dir := range []string{
		cfg.DownloadPath(),
		cfg.LogPath(),
	} {
		log.Println("  ", dir)
		if err := os.MkdirAll(dir, 0700); err != nil {
			return fmt.Errorf("couldn't make directory %q: %v", dir, err)
		}
	}

	// Create root FS tar.
	return nil
}

func exists(path string) bool {
	// This is hacky, but good enough.
	_, err := os.Stat(path)
	return err == nil
}

func generateRSAKey() ([]byte, error) {
	log.Println(
		"WARNING: The generated RSA key SHOULD NOT be used for " +
			"real security, it wasn't generated by a cryptographically secure RNG.")

	key, err := rsa.GenerateKey(&insecureRandomReader{}, 2048)
	if err != nil {
		return nil, fmt.Errorf("couldn't create private key: %v", err)
	}

	pemBlock := pem.EncodeToMemory(&pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	})

	return pemBlock, nil
}

type insecureRandomReader struct {
	once sync.Once
	rand *rand.Rand
}

func (irr *insecureRandomReader) Read(bytes []byte) (int, error) {
	irr.once.Do(func() {
		irr.rand = rand.New(rand.NewSource(time.Now().UnixNano()))
	})

	return irr.rand.Read(bytes)
}
