// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.9.1
// source: ttylog.proto

package ttylog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The FD that the event was written to.
type FD int32

const (
	FD_STDIN  FD = 0
	FD_STDOUT FD = 1
	FD_STDERR FD = 2
)

// Enum value maps for FD.
var (
	FD_name = map[int32]string{
		0: "STDIN",
		1: "STDOUT",
		2: "STDERR",
	}
	FD_value = map[string]int32{
		"STDIN":  0,
		"STDOUT": 1,
		"STDERR": 2,
	}
)

func (x FD) Enum() *FD {
	p := new(FD)
	*p = x
	return p
}

func (x FD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FD) Descriptor() protoreflect.EnumDescriptor {
	return file_ttylog_proto_enumTypes[0].Descriptor()
}

func (FD) Type() protoreflect.EnumType {
	return &file_ttylog_proto_enumTypes[0]
}

func (x FD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FD.Descriptor instead.
func (FD) EnumDescriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{0}
}

type TTYLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp of the log event in micros since the UNIX epoch.
	TimestampMicros int64 `protobuf:"varint,1,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"`
	// Types that are assignable to Event:
	//	*TTYLogEntry_Io
	//	*TTYLogEntry_Close
	Event isTTYLogEntry_Event `protobuf_oneof:"event"`
}

func (x *TTYLogEntry) Reset() {
	*x = TTYLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttylog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTYLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTYLogEntry) ProtoMessage() {}

func (x *TTYLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ttylog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTYLogEntry.ProtoReflect.Descriptor instead.
func (*TTYLogEntry) Descriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{0}
}

func (x *TTYLogEntry) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (m *TTYLogEntry) GetEvent() isTTYLogEntry_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *TTYLogEntry) GetIo() *IO {
	if x, ok := x.GetEvent().(*TTYLogEntry_Io); ok {
		return x.Io
	}
	return nil
}

func (x *TTYLogEntry) GetClose() *Close {
	if x, ok := x.GetEvent().(*TTYLogEntry_Close); ok {
		return x.Close
	}
	return nil
}

type isTTYLogEntry_Event interface {
	isTTYLogEntry_Event()
}

type TTYLogEntry_Io struct {
	Io *IO `protobuf:"bytes,2,opt,name=io,proto3,oneof"`
}

type TTYLogEntry_Close struct {
	Close *Close `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

func (*TTYLogEntry_Io) isTTYLogEntry_Event() {}

func (*TTYLogEntry_Close) isTTYLogEntry_Event() {}

// I/O event on an FD.
type IO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fd   FD     `protobuf:"varint,1,opt,name=fd,proto3,enum=FD" json:"fd,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *IO) Reset() {
	*x = IO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttylog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IO) ProtoMessage() {}

func (x *IO) ProtoReflect() protoreflect.Message {
	mi := &file_ttylog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IO.ProtoReflect.Descriptor instead.
func (*IO) Descriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{1}
}

func (x *IO) GetFd() FD {
	if x != nil {
		return x.Fd
	}
	return FD_STDIN
}

func (x *IO) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Closure of an FD.
type Close struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fd FD `protobuf:"varint,1,opt,name=fd,proto3,enum=FD" json:"fd,omitempty"`
}

func (x *Close) Reset() {
	*x = Close{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttylog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_ttylog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{2}
}

func (x *Close) GetFd() FD {
	if x != nil {
		return x.Fd
	}
	return FD_STDIN
}

var File_ttylog_proto protoreflect.FileDescriptor

var file_ttylog_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x74, 0x79, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78,
	0x0a, 0x0b, 0x54, 0x54, 0x59, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x29, 0x0a,
	0x10, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x15, 0x0a, 0x02, 0x69, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x49, 0x4f, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6f, 0x12,
	0x1e, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x02, 0x49, 0x4f, 0x12, 0x13,
	0x0a, 0x02, 0x66, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x03, 0x2e, 0x46, 0x44, 0x52,
	0x02, 0x66, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1c, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x12, 0x13, 0x0a, 0x02, 0x66, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x03, 0x2e, 0x46,
	0x44, 0x52, 0x02, 0x66, 0x64, 0x2a, 0x27, 0x0a, 0x02, 0x46, 0x44, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x54, 0x44, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x44, 0x4f, 0x55, 0x54,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x44, 0x45, 0x52, 0x52, 0x10, 0x02, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x73,
	0x65, 0x70, 0x68, 0x6c, 0x65, 0x77, 0x69, 0x73, 0x34, 0x32, 0x2f, 0x68, 0x6f, 0x6e, 0x65, 0x79,
	0x73, 0x73, 0x68, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x74, 0x79, 0x6c, 0x6f, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ttylog_proto_rawDescOnce sync.Once
	file_ttylog_proto_rawDescData = file_ttylog_proto_rawDesc
)

func file_ttylog_proto_rawDescGZIP() []byte {
	file_ttylog_proto_rawDescOnce.Do(func() {
		file_ttylog_proto_rawDescData = protoimpl.X.CompressGZIP(file_ttylog_proto_rawDescData)
	})
	return file_ttylog_proto_rawDescData
}

var file_ttylog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ttylog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ttylog_proto_goTypes = []interface{}{
	(FD)(0),             // 0: FD
	(*TTYLogEntry)(nil), // 1: TTYLogEntry
	(*IO)(nil),          // 2: IO
	(*Close)(nil),       // 3: Close
}
var file_ttylog_proto_depIdxs = []int32{
	2, // 0: TTYLogEntry.io:type_name -> IO
	3, // 1: TTYLogEntry.close:type_name -> Close
	0, // 2: IO.fd:type_name -> FD
	0, // 3: Close.fd:type_name -> FD
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ttylog_proto_init() }
func file_ttylog_proto_init() {
	if File_ttylog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ttylog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTYLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttylog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttylog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Close); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ttylog_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TTYLogEntry_Io)(nil),
		(*TTYLogEntry_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ttylog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ttylog_proto_goTypes,
		DependencyIndexes: file_ttylog_proto_depIdxs,
		EnumInfos:         file_ttylog_proto_enumTypes,
		MessageInfos:      file_ttylog_proto_msgTypes,
	}.Build()
	File_ttylog_proto = out.File
	file_ttylog_proto_rawDesc = nil
	file_ttylog_proto_goTypes = nil
	file_ttylog_proto_depIdxs = nil
}
