// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc2
// source: ttylog.proto

package ttylog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The FD that the event was written to.
type FD int32

const (
	FD_STDIN  FD = 0
	FD_STDOUT FD = 1
	FD_STDERR FD = 2
)

// Enum value maps for FD.
var (
	FD_name = map[int32]string{
		0: "STDIN",
		1: "STDOUT",
		2: "STDERR",
	}
	FD_value = map[string]int32{
		"STDIN":  0,
		"STDOUT": 1,
		"STDERR": 2,
	}
)

func (x FD) Enum() *FD {
	p := new(FD)
	*p = x
	return p
}

func (x FD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FD) Descriptor() protoreflect.EnumDescriptor {
	return file_ttylog_proto_enumTypes[0].Descriptor()
}

func (FD) Type() protoreflect.EnumType {
	return &file_ttylog_proto_enumTypes[0]
}

func (x FD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FD.Descriptor instead.
func (FD) EnumDescriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{0}
}

type TTYLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the log event in micros since the UNIX epoch.
	TimestampMicros int64 `protobuf:"varint,1,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*TTYLogEntry_Io
	//	*TTYLogEntry_Close
	Event         isTTYLogEntry_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTYLogEntry) Reset() {
	*x = TTYLogEntry{}
	mi := &file_ttylog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTYLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTYLogEntry) ProtoMessage() {}

func (x *TTYLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ttylog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTYLogEntry.ProtoReflect.Descriptor instead.
func (*TTYLogEntry) Descriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{0}
}

func (x *TTYLogEntry) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (x *TTYLogEntry) GetEvent() isTTYLogEntry_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TTYLogEntry) GetIo() *IO {
	if x != nil {
		if x, ok := x.Event.(*TTYLogEntry_Io); ok {
			return x.Io
		}
	}
	return nil
}

func (x *TTYLogEntry) GetClose() *Close {
	if x != nil {
		if x, ok := x.Event.(*TTYLogEntry_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isTTYLogEntry_Event interface {
	isTTYLogEntry_Event()
}

type TTYLogEntry_Io struct {
	Io *IO `protobuf:"bytes,2,opt,name=io,proto3,oneof"`
}

type TTYLogEntry_Close struct {
	Close *Close `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

func (*TTYLogEntry_Io) isTTYLogEntry_Event() {}

func (*TTYLogEntry_Close) isTTYLogEntry_Event() {}

// I/O event on an FD.
type IO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            FD                     `protobuf:"varint,1,opt,name=fd,proto3,enum=FD" json:"fd,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IO) Reset() {
	*x = IO{}
	mi := &file_ttylog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IO) ProtoMessage() {}

func (x *IO) ProtoReflect() protoreflect.Message {
	mi := &file_ttylog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IO.ProtoReflect.Descriptor instead.
func (*IO) Descriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{1}
}

func (x *IO) GetFd() FD {
	if x != nil {
		return x.Fd
	}
	return FD_STDIN
}

func (x *IO) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Closure of an FD.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            FD                     `protobuf:"varint,1,opt,name=fd,proto3,enum=FD" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_ttylog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_ttylog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_ttylog_proto_rawDescGZIP(), []int{2}
}

func (x *Close) GetFd() FD {
	if x != nil {
		return x.Fd
	}
	return FD_STDIN
}

var File_ttylog_proto protoreflect.FileDescriptor

const file_ttylog_proto_rawDesc = "" +
	"\n" +
	"\fttylog.proto\"x\n" +
	"\vTTYLogEntry\x12)\n" +
	"\x10timestamp_micros\x18\x01 \x01(\x03R\x0ftimestampMicros\x12\x15\n" +
	"\x02io\x18\x02 \x01(\v2\x03.IOH\x00R\x02io\x12\x1e\n" +
	"\x05close\x18\x03 \x01(\v2\x06.CloseH\x00R\x05closeB\a\n" +
	"\x05event\"-\n" +
	"\x02IO\x12\x13\n" +
	"\x02fd\x18\x01 \x01(\x0e2\x03.FDR\x02fd\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1c\n" +
	"\x05Close\x12\x13\n" +
	"\x02fd\x18\x01 \x01(\x0e2\x03.FDR\x02fd*'\n" +
	"\x02FD\x12\t\n" +
	"\x05STDIN\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02B/Z-github.com/josephlewis42/honeyssh/core/ttylogb\x06proto3"

var (
	file_ttylog_proto_rawDescOnce sync.Once
	file_ttylog_proto_rawDescData []byte
)

func file_ttylog_proto_rawDescGZIP() []byte {
	file_ttylog_proto_rawDescOnce.Do(func() {
		file_ttylog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ttylog_proto_rawDesc), len(file_ttylog_proto_rawDesc)))
	})
	return file_ttylog_proto_rawDescData
}

var file_ttylog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ttylog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ttylog_proto_goTypes = []any{
	(FD)(0),             // 0: FD
	(*TTYLogEntry)(nil), // 1: TTYLogEntry
	(*IO)(nil),          // 2: IO
	(*Close)(nil),       // 3: Close
}
var file_ttylog_proto_depIdxs = []int32{
	2, // 0: TTYLogEntry.io:type_name -> IO
	3, // 1: TTYLogEntry.close:type_name -> Close
	0, // 2: IO.fd:type_name -> FD
	0, // 3: Close.fd:type_name -> FD
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ttylog_proto_init() }
func file_ttylog_proto_init() {
	if File_ttylog_proto != nil {
		return
	}
	file_ttylog_proto_msgTypes[0].OneofWrappers = []any{
		(*TTYLogEntry_Io)(nil),
		(*TTYLogEntry_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ttylog_proto_rawDesc), len(file_ttylog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ttylog_proto_goTypes,
		DependencyIndexes: file_ttylog_proto_depIdxs,
		EnumInfos:         file_ttylog_proto_enumTypes,
		MessageInfos:      file_ttylog_proto_msgTypes,
	}.Build()
	File_ttylog_proto = out.File
	file_ttylog_proto_goTypes = nil
	file_ttylog_proto_depIdxs = nil
}
